[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Nixpacks configuration for Node.js 20
[nixpacks.phases.setup]
nixPkgs = ["nodejs_20", "npm-10_x"]

# Environment variables
[env]
NODE_ENV = "production"
PORT = { default = "3000" }
NIXPACKS_NODEJS_VERSION = "20"